# 对应feign接口调用时 连接时间和读取时间等的配置
spring:
  cloud:
    openfeign:
      client:
        config:
#          需要配置指定微服务的连接时间和读取时间
          service-product:
            logger-level: full
            connect-timeout: 3000
            read-timeout: 5000
#            如果每个微服务都单独配置就太麻烦了，这里就提供了默认值
          default:
            logger-level: full
            connect-timeout: 1000
            read-timeout: 2000
    sentinel:
      transport:
        dashboard: localhost:8080
#     sentinel 控制台默认是懒加载，控制台不会主动加载注册的服务，这里设置成非懒加载
      eager: true
feign:
  sentinel:
    enabled: true