server:
  port: 8000

spring:
  profiles:
#    激活某一个环境
    active: dev
#    包含 feign 环境的配置文件
    include: feign
  application:
    name: service-order
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        namespace: ${spring.profiles.active:d773890e-2efb-40a7-8b93-dce26ba02b26}
#          以前是默认写死的值，写的命名空间ID
#        namespace: d773890e-2efb-40a7-8b93-dce26ba02b26


# Fegin 日志打印，指定包才会打印
logging:
  level:
    com.luojia.order: debug

# 分隔配置文件
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: dev
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: test
---
spring:
  config:
    import:
      - nacos:common.properties?group=order
      - nacos:database.properties?group=order
    activate:
      on-profile: prod